package game.iqlink.gui;

/**
 * Created by jiaye on 16-9-22.
 */
public class startPlacement {

        /** this is all solutions for IQ-Link, generated from MDZZ.java**/
        static String[] SOLUTIONS = {
                "KAFUBAHCIPDALEFEFEQGHSHBWIJAJKGKLILI",
                "IAFBBGVCAJDJGEDQFEUGIRHKIIHFJGNKFOLG",
                "GAEWBABCDJDALEFMFCCGLUHBTIAQJCKKBILF",
                "JAAPBGVCJRDCHEFSFBWGBFHEGIICJDDKKOLF",
                "KAAHBLTCAODEFEGMFCEGEQHDBIGXJHDKFJLF",
                "KAAHBLTCAODEFEGMFCEGERHGBIGVJIDKFJLF",
                "KAFUBAICCPDALEFEFEQGHSHBNIBCJFRKEGLI",
                "JAAPBGVCJRDCDEDSFBWGBFHECIFAJDOKFHLG",
                "KAFCBGUCAGDFLEFPFBBGESHBWIJKJAHKLJLH",
                "JACRBHQCHCDGDELVFJBGESHBUIAFJEHKLGLL",
                "JAAPBGVCJRDCDEDSFBWGBFHECIFAJDHKGOLF",
                "IAFBBGVCAJDJGEDQFEUGIRHCIIHFJGNKFOLG",
                "KAFCBGUCAGDFLEFPFBBGESHBOIAKJARKEJLH",
                "KAAHBLTCAODEFEGMFCEGERHGBIGVJCDKFJLF",
                "JADVBJBCJRDCDEDHFEWGBFHEJILSJCOKLMLC",
                "JABHBCBCGGDFIEKVFAFGGSHBXIAJJJUKHKLK",
                "IAFBBDRCEPDEWEBSFJTGBFHGGILIJAQKIJLI",
                "KAFUBAICCPDALEFEFEQGHSHBNIBCJFGKIRLE",
                "KAFTBAICFRDCEELWFJJGDMHKCIGNJCPKEBLF",
                "JADVBJBCJRDCDEDSFBWGBFHEJILGJEOKLHLE",
                "KAAHBLTCAODEFEGMFCEGEVHBBIGXJADKFJLF",
                "KAFUBAHCIPDALEFEFEQGHSHBWIJBJFGKEILI",
        };
}
